// Generated by scripts/generate-code-shell-types.cjs from remote-protocol.
// Do not edit directly.

export interface CodeShellState {
  language: string;
  modules: CodeShellModule[];
  projects: CodeShellProject[];
  currentProjectId: string | null;
  projectBusy: boolean;
  account: CodeShellAccount;
}

export interface CodeShellModule {
  id: string;
  label: string;
}

export interface CodeShellProject {
  id: string;
  name: string;
  path: string;
}

export interface CodeShellAccount {
  name: string;
  plan: string;
  allowance: string;
  remainingPercent: number | null;
}

export type CodeShellAction =
  | { kind: "select-module"; id: string }
  | { kind: "select-project"; id: string }
  | { kind: "add-project" }
  | { kind: "reveal-project" }
  | { kind: "settings" }
  | { kind: "sign-out" };
