import { hasNativeBackend, invoke, listen } from "../api/transport";
import type { FigureConnections, FigureDocument, FigureRasterDocument, FigureView, PrepareFigure } from "./types";

export const figuresAvailable = hasNativeBackend;
export const figuresRunningCount = () => invoke<number>("figures_running_count");
export const figureConnections = (model: string | null = null, reviewerModel: string | null = null) => invoke<FigureConnections>("figures_connections", { model, reviewerModel });
export const figureList = (projectId: string) => invoke<FigureView[]>("figures_list", { projectId });
export const figurePrepare = (input: PrepareFigure) => invoke<FigureView>("figures_prepare", { input });
export const figureStart = (projectId: string, id: string, expectedSourceHash: string | null = null, expectedSourceIndex: number | null = null) => invoke<FigureView>("figures_start", { projectId, id, expectedSourceHash, expectedSourceIndex });
export const figureRasterDocument = (projectId: string, id: string, index: number | null = null) => invoke<FigureRasterDocument>("figures_raster_document", { projectId, id, index });
export const figureSelectRaster = (projectId: string, id: string, index: number, expectedHash: string) => invoke<FigureView>("figures_select_raster", { projectId, id, index, expectedHash });
export const figureEditImage = (input: { projectId: string; id: string; baseIndex: number; expectedHash: string; prompt: string; maskBase64: string }) => invoke<FigureView>("figures_edit_image", { input });
export type ImageResultChoice = "returned" | "selection" | "keep";
export const figureEditResultDocument = (projectId: string, id: string, requestId: string, expectedHash: string, choice: Exclude<ImageResultChoice, "keep">) => invoke<FigureRasterDocument>("figures_edit_result_document", { projectId, id, requestId, expectedHash, choice });
export const figureResolveEditResult = (projectId: string, id: string, requestId: string, expectedHash: string, choice: ImageResultChoice) => invoke<FigureView>("figures_resolve_edit_result", { projectId, id, requestId, expectedHash, choice });
export const figureExportRaster = (projectId: string, id: string, index: number, destination: string | null) => invoke<{ filename: string; mimeType: string; dataBase64: string }>("figures_export_raster", { projectId, id, index, destination });
export const figureDelete = (projectId: string, id: string) => invoke<void>("figures_delete", { projectId, id });
export const figureCancel = (projectId: string, id: string) => invoke<void>("figures_cancel", { projectId, id });
export const figureReview = (projectId: string, id: string) => invoke<FigureView>("figures_review", { projectId, id });
export const figureEditSvg = (input: { projectId: string; id: string; editId: string; baseIndex: number; expectedHash: string; prompt: string }) => invoke<FigureView>("figures_edit_svg", { input });
export const figureDocument = (projectId: string, id: string, versionIndex: number | null = null) => invoke<FigureDocument>("figures_document", { projectId, id, versionIndex });
export const figureSave = (projectId: string, id: string, expectedHash: string | null, svg: string, baseIndex: number | null = null) => invoke<FigureView>("figures_save", { projectId, id, expectedHash, svg, baseIndex });
export const figureExport = (projectId: string, id: string, format: string, destination: string | null, versionIndex: number | null = null) => invoke<{ filename: string; mimeType: string; dataBase64: string }>("figures_export", { projectId, id, format, destination, versionIndex });
export const onFigureUpdated = (handler: (view: FigureView) => void) => listen("figures-updated", (event) => handler(event.payload as FigureView));
