[package]
name = "aris-executor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
api = { path = "../api" }
reqwest = { version = "0.12", default-features = false, features = ["json", "native-tls"] }
runtime = { path = "../runtime" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "time"] }

[lints]
workspace = true
