//! Image Assist wire protocol.
//!
//! Image Assist brokers one image-generation request between two desktops that
//! have never paired and belong to different people. It deliberately does not
//! reuse [`crate::ComputeWireMessage`]: that enum is dispatched by a handler
//! that also serves compute jobs and Agent control requests, so carrying Image
//! Assist inside it would place a brokered stranger on the general compute
//! channel. This module therefore defines a closed message set whose serde tags
//! do not overlap any compute or control tag, so a payload from one protocol
//! cannot decode as the other even before type-level routing is considered.
//!
//! See `docs/development-logic/image-assist-network.md`.

use crate::pairing::append_string;
use crate::{
    Base64UrlBytes, DeviceDescriptor, DeviceId, DeviceSignature, DeviceSigningKey, MatchId,
    PairingError, ProtocolVersion, RequestId, SessionId, CURRENT_PROTOCOL_VERSION,
};
use serde::{Deserialize, Serialize};

/// Domain separator for the Image Assist match transcript.
const MATCH_TRANSCRIPT_LABEL: &[u8] = b"somniq-image-assist/match-transcript/v1";

/// Maximum number of ICE server URLs a brokered match may carry, matching the
/// gateway's own pairing STUN bound.
pub const IMAGE_ASSIST_MAX_ICE_SERVERS: usize = 8;

/// Maximum UTF-8 byte length of a brokered prompt.
///
/// The tool schema permits 120,000 *characters*, which for CJK text exceeds
/// both the gateway frame cap and any plausible image prompt. Brokered requests
/// are bounded in bytes and validated before the prompt leaves the requester.
pub const IMAGE_ASSIST_MAX_PROMPT_BYTES: usize = 8 * 1024;

/// Maximum UTF-8 byte length of an aspect-ratio label such as `16:9`.
pub const IMAGE_ASSIST_MAX_ASPECT_RATIO_BYTES: usize = 16;

/// Maximum number of images one brokered request may return.
pub const IMAGE_ASSIST_MAX_ARTIFACTS: usize = 8;

/// Maximum size of a single returned image.
///
/// Deliberately below the local Oracle ceiling because the sender is a
/// stranger rather than the local user's own account.
pub const IMAGE_ASSIST_MAX_ARTIFACT_BYTES: u64 = 16 * 1024 * 1024;

/// Maximum combined size of all images in one brokered request.
pub const IMAGE_ASSIST_MAX_TOTAL_ARTIFACT_BYTES: u64 = 32 * 1024 * 1024;

/// Maximum artifact transfer chunk, matching the compute artifact chunk so both
/// stay below the gateway relay frame cap.
pub const IMAGE_ASSIST_MAX_ARTIFACT_CHUNK_BYTES: usize = 128 * 1024;

/// Maximum length of a generated artifact name.
pub const IMAGE_ASSIST_MAX_ARTIFACT_NAME_BYTES: usize = 64;

/// The only image types a brokered helper may return.
const ALLOWED_MIME_TYPES: [&str; 3] = ["image/png", "image/jpeg", "image/webp"];

/// The only file extensions a brokered artifact name may carry.
const ALLOWED_EXTENSIONS: [&str; 4] = ["png", "jpg", "jpeg", "webp"];

/// One image returned by a helper, described without any helper-local detail.
///
/// The helper never forwards its own `OracleWebImageView`: that structure
/// carries the helper's account id, ChatGPT session id, prose output, and
/// absolute local paths. `name` is generated by the helper from an index and
/// the detected type, never derived from a filesystem path.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ImageArtifactEntry {
    pub name: String,
    pub size_bytes: u64,
    pub mime: String,
    pub sha256: String,
}

impl ImageArtifactEntry {
    /// Validates one manifest entry in isolation.
    ///
    /// This is enforced on both ends: the helper must not emit an invalid
    /// entry, and the requester must not trust one it received.
    pub fn validate(&self) -> Result<(), ImageAssistError> {
        validate_artifact_name(&self.name)?;
        if !ALLOWED_MIME_TYPES.contains(&self.mime.as_str()) {
            return Err(ImageAssistError::UnsupportedMimeType);
        }
        if self.size_bytes == 0 {
            return Err(ImageAssistError::EmptyArtifact);
        }
        if self.size_bytes > IMAGE_ASSIST_MAX_ARTIFACT_BYTES {
            return Err(ImageAssistError::ArtifactTooLarge);
        }
        validate_sha256_hex(&self.sha256)?;
        Ok(())
    }
}

/// Validates a complete manifest, including cross-entry rules.
///
/// A duplicate name fails the whole manifest rather than the entry, because a
/// requester that silently dropped a duplicate would write fewer files than the
/// manifest promised and could be steered into overwriting one of them.
pub fn validate_artifact_manifest(
    artifacts: &[ImageArtifactEntry],
) -> Result<(), ImageAssistError> {
    if artifacts.is_empty() {
        return Err(ImageAssistError::EmptyManifest);
    }
    if artifacts.len() > IMAGE_ASSIST_MAX_ARTIFACTS {
        return Err(ImageAssistError::TooManyArtifacts);
    }
    let mut total: u64 = 0;
    for (index, artifact) in artifacts.iter().enumerate() {
        artifact.validate()?;
        if artifacts[..index]
            .iter()
            .any(|earlier| earlier.name == artifact.name)
        {
            return Err(ImageAssistError::DuplicateArtifactName);
        }
        total = total
            .checked_add(artifact.size_bytes)
            .ok_or(ImageAssistError::ManifestTooLarge)?;
    }
    if total > IMAGE_ASSIST_MAX_TOTAL_ARTIFACT_BYTES {
        return Err(ImageAssistError::ManifestTooLarge);
    }
    Ok(())
}

/// Validates a brokered artifact name before it is used for any filesystem
/// operation.
///
/// The name must be a plain lowercase file name: no separators, no parent
/// references, no leading dot, no drive letter, and one allowed extension.
pub fn validate_artifact_name(name: &str) -> Result<(), ImageAssistError> {
    if name.is_empty() || name.len() > IMAGE_ASSIST_MAX_ARTIFACT_NAME_BYTES {
        return Err(ImageAssistError::InvalidArtifactName);
    }
    if name.starts_with('.') || name.starts_with('-') {
        return Err(ImageAssistError::InvalidArtifactName);
    }
    let Some((stem, extension)) = name.rsplit_once('.') else {
        return Err(ImageAssistError::InvalidArtifactName);
    };
    if stem.is_empty() || !ALLOWED_EXTENSIONS.contains(&extension) {
        return Err(ImageAssistError::InvalidArtifactName);
    }
    if !stem
        .bytes()
        .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
    {
        return Err(ImageAssistError::InvalidArtifactName);
    }
    Ok(())
}

fn validate_sha256_hex(value: &str) -> Result<(), ImageAssistError> {
    if value.len() != 64
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(ImageAssistError::InvalidDigest);
    }
    Ok(())
}

/// Which side of a brokered match creates the WebRTC offer.
///
/// Paired computers derive this from the pairing direction. Strangers have no
/// pairing direction, so the gateway assigns it and both sides sign the
/// assignment: without that, a gateway could silently make both peers offer or
/// both answer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum P2pRole {
    Offerer,
    Answerer,
}

/// The parameters of one brokered match, signed by both peers.
///
/// Signature verification uses Ed25519 device signing keys and therefore does
/// not depend on the session key it attests, so there is no bootstrap
/// circularity. A fully malicious gateway can still forge both introductions;
/// what this defeats is tampering by anyone else, and it forces the gateway
/// from passive key substitution into active forgery.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ImageAssistTranscript {
    pub protocol_version: ProtocolVersion,
    pub match_id: MatchId,
    /// Full descriptors, not just ids and keys: the approval dialog shows the
    /// peer's kind and display name, so those must be authenticated too.
    pub requester: DeviceDescriptor,
    pub helper: DeviceDescriptor,
    /// The device the gateway assigned the offerer role to.
    pub offerer: DeviceId,
    /// The transport session this transcript opens. The relay fallback carries
    /// its own session id and therefore re-runs the exchange rather than
    /// reusing a signature made for the failed direct attempt.
    pub session_id: SessionId,
    pub ice_servers: Vec<String>,
    pub expires_at_unix_ms: i64,
    /// SHA-256 of the canonical preview plaintext the helper approved.
    pub request_digest: [u8; 32],
}

impl ImageAssistTranscript {
    /// Validates the fields that must hold before a transcript is signed or
    /// trusted.
    pub fn validate(&self) -> Result<(), ImageAssistError> {
        if self.protocol_version != CURRENT_PROTOCOL_VERSION {
            return Err(ImageAssistError::UnsupportedProtocol);
        }
        if self.requester.device_id == self.helper.device_id {
            return Err(ImageAssistError::SameDeviceMatch);
        }
        if self.offerer != self.requester.device_id && self.offerer != self.helper.device_id {
            return Err(ImageAssistError::UnknownOfferer);
        }
        if self.ice_servers.len() > IMAGE_ASSIST_MAX_ICE_SERVERS {
            return Err(ImageAssistError::TooManyIceServers);
        }
        // Sorted and deduplicated so both peers produce identical bytes
        // regardless of the order the gateway delivered them in.
        if self.ice_servers.windows(2).any(|pair| pair[0] >= pair[1]) {
            return Err(ImageAssistError::UnsortedIceServers);
        }
        Ok(())
    }

    /// Returns the role this transcript assigns to one device.
    pub fn role_of(&self, device_id: DeviceId) -> Option<P2pRole> {
        if device_id != self.requester.device_id && device_id != self.helper.device_id {
            return None;
        }
        Some(if device_id == self.offerer {
            P2pRole::Offerer
        } else {
            P2pRole::Answerer
        })
    }

    /// Builds the canonical signed byte sequence.
    ///
    /// Deterministic and length-prefixed, using the same descriptor encoding as
    /// every pairing transcript. It is never derived from serde output, which
    /// would make the signed bytes depend on field order and formatting.
    pub fn signature_transcript(&self) -> Result<Vec<u8>, ImageAssistError> {
        self.validate()?;
        let mut output = Vec::with_capacity(384);
        output.extend_from_slice(MATCH_TRANSCRIPT_LABEL);
        output.extend_from_slice(&self.protocol_version.as_u16().to_be_bytes());
        output.extend_from_slice(self.match_id.as_uuid().as_bytes());
        append_descriptor(&mut output, &self.requester)?;
        append_descriptor(&mut output, &self.helper)?;
        output.extend_from_slice(self.offerer.as_uuid().as_bytes());
        output.extend_from_slice(self.session_id.as_uuid().as_bytes());
        output.push(
            u8::try_from(self.ice_servers.len())
                .map_err(|_| ImageAssistError::TooManyIceServers)?,
        );
        for server in &self.ice_servers {
            append_string(&mut output, server).map_err(image_assist_transcript_error)?;
        }
        output.extend_from_slice(&self.expires_at_unix_ms.to_be_bytes());
        output.extend_from_slice(&self.request_digest);
        Ok(output)
    }

    /// Signs this transcript with a device signing key.
    pub fn sign(
        &self,
        signing_key: &DeviceSigningKey,
    ) -> Result<DeviceSignature, ImageAssistError> {
        Ok(signing_key.sign(&self.signature_transcript()?))
    }

    /// Verifies a peer's proof over this transcript.
    ///
    /// `signer` must be one of the two descriptors the transcript names, so a
    /// third device cannot present a valid signature over someone else's match.
    pub fn verify(
        &self,
        signer: DeviceId,
        proof: &DeviceSignature,
    ) -> Result<(), ImageAssistError> {
        let descriptor = if signer == self.requester.device_id {
            &self.requester
        } else if signer == self.helper.device_id {
            &self.helper
        } else {
            return Err(ImageAssistError::UnknownSigner);
        };
        descriptor
            .signing_public_key
            .verify(&self.signature_transcript()?, proof)
            .map_err(|_| ImageAssistError::InvalidTranscriptProof)
    }
}

fn append_descriptor(
    output: &mut Vec<u8>,
    descriptor: &DeviceDescriptor,
) -> Result<(), ImageAssistError> {
    descriptor
        .append_signature_bytes(output)
        .map_err(image_assist_transcript_error)
}

fn image_assist_transcript_error(error: PairingError) -> ImageAssistError {
    match error {
        PairingError::TranscriptFieldTooLong => ImageAssistError::TranscriptFieldTooLong,
        _ => ImageAssistError::InvalidDescriptor,
    }
}

/// One row of the online-helper roster shown to a requester.
///
/// Anonymous by default. A helper who volunteers to serve strangers has not
/// thereby agreed to publish its device name, which frequently contains a real
/// person's name.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ImageAssistRosterEntry {
    /// Short, stable, non-identifying label. Enough to distinguish rows and to
    /// cross-reference an audit record; not enough to identify a person.
    pub fingerprint: String,
    /// Present only when the helper explicitly opted in to being named.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Optional user-approved coarse location. Coordinates are intentionally
    /// rounded by the desktop before they reach the gateway.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<ImageAssistLocation>,
    pub available: bool,
}

/// A coarse, user-approved location for presence visualization.
///
/// This is never inferred by the gateway and is absent unless the helper
/// explicitly enables location sharing. A one-decimal coordinate is roughly
/// city-scale and avoids exposing a home address.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ImageAssistLocation {
    pub label: String,
    pub latitude: f32,
    pub longitude: f32,
}

impl ImageAssistLocation {
    pub fn validate(&self) -> Result<(), ImageAssistError> {
        if self.label.trim().is_empty() || self.label.len() > 80 {
            return Err(ImageAssistError::InvalidLocation);
        }
        if !self.latitude.is_finite()
            || !self.longitude.is_finite()
            || !(-90.0..=90.0).contains(&self.latitude)
            || !(-180.0..=180.0).contains(&self.longitude)
        {
            return Err(ImageAssistError::InvalidLocation);
        }
        Ok(())
    }

    /// Normalizes an advertised point to city-scale precision.
    pub fn coarsened(mut self) -> Result<Self, ImageAssistError> {
        self.validate()?;
        self.label = self.label.trim().to_string();
        self.latitude = (self.latitude * 10.0).round() / 10.0;
        self.longitude = (self.longitude * 10.0).round() / 10.0;
        Ok(self)
    }
}

/// Why a brokered attempt did not produce a match.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MatchFailure {
    /// No helper is online, available, and willing.
    NoHelper,
    /// Every candidate declined.
    Declined,
    /// The match deadline passed before approval.
    Timeout,
    /// The requester exceeded its rolling budget.
    RateLimited,
    /// The requester already has a brokered request in flight.
    Busy,
    /// Either side cancelled.
    Cancelled,
}

/// Brokering frames a desktop sends to the gateway on the signal channel.
///
/// Defined here rather than in the gateway so both ends compile against one
/// definition. The existing signal frames are mirrored by hand on each side,
/// which is a known drift risk; this surface deliberately does not repeat it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum ImageAssistClientFrame {
    /// Advertise or renew willingness to serve. There is no slot count: the
    /// desktop serializes every Oracle job behind one global lock.
    HelperReady {
        lease_ms: u32,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        display_name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        location: Option<ImageAssistLocation>,
    },
    /// Extends an existing advertisement without re-sending or changing any
    /// optional public profile metadata. If the gateway lost process-local
    /// presence during a restart, it recreates an anonymous advertisement.
    HelperRenew {
        lease_ms: u32,
    },
    HelperStopped,
    RequestRoster,
    RequestHelper {
        request_id: RequestId,
    },
    /// The prompt, sealed to the helper's key-agreement public key. The gateway
    /// relays these bytes without inspecting them.
    Preview {
        match_id: MatchId,
        sealed: Base64UrlBytes,
    },
    Decision {
        match_id: MatchId,
        accept: bool,
    },
    RelaySession {
        match_id: MatchId,
    },
    Cancel {
        match_id: MatchId,
    },
    Closed {
        match_id: MatchId,
    },
}

/// Brokering frames the gateway sends to a desktop.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum ImageAssistServerFrame {
    Roster {
        entries: Vec<ImageAssistRosterEntry>,
    },
    /// To the requester only: enough to seal a preview, and nothing more. No
    /// transport identifier exists at this point.
    Candidate {
        match_id: MatchId,
        peer: DeviceDescriptor,
        expires_at_unix_ms: i64,
    },
    /// To the helper: the requester's descriptor plus the opaque sealed prompt
    /// to open and display before deciding.
    Offered {
        match_id: MatchId,
        peer: DeviceDescriptor,
        sealed: Base64UrlBytes,
        expires_at_unix_ms: i64,
    },
    /// Sent to both sides only after the helper approved. This is the first
    /// frame carrying any transport identifier.
    Approved {
        match_id: MatchId,
        offerer: DeviceId,
        session_id: SessionId,
        ice_servers: Vec<String>,
        expires_at_unix_ms: i64,
    },
    RelaySessionGranted {
        match_id: MatchId,
        relay_session_id: SessionId,
    },
    MatchFailed {
        request_id: RequestId,
        reason: MatchFailure,
    },
    MatchClosed {
        match_id: MatchId,
        reason: MatchFailure,
    },
    /// Sent to both parties after the requester imported every image and
    /// explicitly closed the one-shot session.
    Completed {
        match_id: MatchId,
    },
    Error {
        message: String,
    },
}

/// Why a brokered request ended without images.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ImageAssistFailure {
    /// The helper's local user declined after seeing the prompt.
    Declined,
    /// The helper's ChatGPT account was no longer usable.
    HelperUnavailable,
    /// The delivered request did not match the approved preview.
    RequestMismatch,
    /// Image generation failed on the helper.
    GenerationFailed,
    /// Either side cancelled.
    Cancelled,
    /// The match deadline passed.
    Expired,
}

/// The closed message set carried on an Image Assist channel.
///
/// Every serde tag is prefixed so that no value collides with a
/// [`crate::ComputeWireMessage`] tag. `ArtifactRead` and `ArtifactChunk` in
/// particular exist in both protocols, and the prefix keeps a compute frame
/// from being mistaken for a brokered one at the encoding layer as well as at
/// the type layer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ImageAssistWireMessage {
    /// The signed match parameters, exchanged as the first message on every
    /// Image Assist channel. Neither side sends anything else until it has
    /// verified the peer's copy against its own.
    ///
    /// Boxed because a transcript embeds two full device descriptors and every
    /// other variant is an order of magnitude smaller.
    #[serde(rename = "image_transcript")]
    Transcript {
        transcript: Box<ImageAssistTranscript>,
        proof: DeviceSignature,
    },
    /// The approved image request. Its digest must equal the digest of the
    /// preview the helper approved.
    #[serde(rename = "image_request")]
    Request {
        request_id: RequestId,
        prompt: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        aspect_ratio: Option<String>,
    },
    /// The helper has accepted the request and started generating.
    #[serde(rename = "image_accepted")]
    Accepted { request_id: RequestId },
    /// Generation finished; the sanitized manifest names what can be read.
    #[serde(rename = "image_result")]
    Result {
        request_id: RequestId,
        artifacts: Vec<ImageArtifactEntry>,
    },
    /// Requester asks for one bounded slice of one named artifact.
    #[serde(rename = "image_artifact_read")]
    ArtifactRead {
        request_id: RequestId,
        name: String,
        offset: u64,
        max_bytes: u32,
    },
    /// One bounded slice of one named artifact.
    #[serde(rename = "image_artifact_chunk")]
    ArtifactChunk {
        request_id: RequestId,
        name: String,
        offset: u64,
        data: Base64UrlBytes,
        eof: bool,
        sha256: String,
    },
    /// Either side ends the request.
    #[serde(rename = "image_failed")]
    Failed {
        request_id: RequestId,
        reason: ImageAssistFailure,
    },
}

impl ImageAssistWireMessage {
    /// Validates one decoded frame before it reaches any state machine.
    pub fn validate(&self) -> Result<(), ImageAssistError> {
        match self {
            Self::Transcript { transcript, .. } => transcript.validate(),
            Self::Request {
                prompt,
                aspect_ratio,
                ..
            } => {
                if prompt.trim().is_empty() {
                    return Err(ImageAssistError::EmptyPrompt);
                }
                if prompt.len() > IMAGE_ASSIST_MAX_PROMPT_BYTES {
                    return Err(ImageAssistError::PromptTooLong);
                }
                if let Some(ratio) = aspect_ratio {
                    if ratio.is_empty() || ratio.len() > IMAGE_ASSIST_MAX_ASPECT_RATIO_BYTES {
                        return Err(ImageAssistError::InvalidAspectRatio);
                    }
                }
                Ok(())
            }
            Self::Result { artifacts, .. } => validate_artifact_manifest(artifacts),
            Self::ArtifactRead {
                name, max_bytes, ..
            } => {
                validate_artifact_name(name)?;
                if *max_bytes == 0 || *max_bytes as usize > IMAGE_ASSIST_MAX_ARTIFACT_CHUNK_BYTES {
                    return Err(ImageAssistError::InvalidChunkRequest);
                }
                Ok(())
            }
            Self::ArtifactChunk {
                name, data, sha256, ..
            } => {
                validate_artifact_name(name)?;
                if data.as_bytes().len() > IMAGE_ASSIST_MAX_ARTIFACT_CHUNK_BYTES {
                    return Err(ImageAssistError::ChunkTooLarge);
                }
                validate_sha256_hex(sha256)
            }
            Self::Accepted { .. } | Self::Failed { .. } => Ok(()),
        }
    }
}

/// Validation failures for brokered image traffic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum ImageAssistError {
    #[error("the shared approximate location is invalid")]
    InvalidLocation,
    #[error("the brokered prompt is empty")]
    EmptyPrompt,
    #[error("the brokered prompt exceeds {IMAGE_ASSIST_MAX_PROMPT_BYTES} UTF-8 bytes")]
    PromptTooLong,
    #[error("the aspect ratio label is invalid")]
    InvalidAspectRatio,
    #[error("the artifact manifest is empty")]
    EmptyManifest,
    #[error("the artifact manifest exceeds {IMAGE_ASSIST_MAX_ARTIFACTS} entries")]
    TooManyArtifacts,
    #[error("the artifact manifest exceeds the total size limit")]
    ManifestTooLarge,
    #[error("two artifacts share one name")]
    DuplicateArtifactName,
    #[error("the artifact name is not a plain image file name")]
    InvalidArtifactName,
    #[error("the artifact MIME type is not an allowed image type")]
    UnsupportedMimeType,
    #[error("the artifact is empty")]
    EmptyArtifact,
    #[error("the artifact exceeds the brokered size limit")]
    ArtifactTooLarge,
    #[error("the digest is not lowercase hexadecimal SHA-256")]
    InvalidDigest,
    #[error("the artifact chunk request is out of bounds")]
    InvalidChunkRequest,
    #[error("the artifact chunk exceeds the transfer limit")]
    ChunkTooLarge,
    #[error("the match transcript uses an unsupported protocol version")]
    UnsupportedProtocol,
    #[error("a match requires two distinct devices")]
    SameDeviceMatch,
    #[error("the assigned offerer is not a party to this match")]
    UnknownOfferer,
    #[error("the match carries more ICE servers than the protocol allows")]
    TooManyIceServers,
    #[error("the match ICE server list is not sorted and deduplicated")]
    UnsortedIceServers,
    #[error("a match transcript field is too long")]
    TranscriptFieldTooLong,
    #[error("the match transcript carries an invalid device descriptor")]
    InvalidDescriptor,
    #[error("the transcript signer is not a party to this match")]
    UnknownSigner,
    #[error("the match transcript proof did not verify")]
    InvalidTranscriptProof,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        ComputeJobId, ComputeWireMessage, DeviceKind, KeyAgreementSecret, PreviewKeyContext,
        SessionKeyContext,
    };

    fn digest() -> String {
        "a".repeat(64)
    }

    #[test]
    fn shared_locations_are_validated_and_reduced_to_city_scale() {
        let location = ImageAssistLocation {
            label: " Mexico City ".to_string(),
            latitude: 19.432_608,
            longitude: -99.133_21,
        }
        .coarsened()
        .expect("valid location");
        assert_eq!(location.label, "Mexico City");
        assert_eq!(location.latitude, 19.4);
        assert_eq!(location.longitude, -99.1);

        assert!(ImageAssistLocation {
            label: "somewhere".to_string(),
            latitude: 91.0,
            longitude: 0.0,
        }
        .coarsened()
        .is_err());
    }

    struct TestDevice {
        descriptor: DeviceDescriptor,
        signing: DeviceSigningKey,
        agreement: KeyAgreementSecret,
    }

    fn device(name: &str) -> TestDevice {
        let signing = DeviceSigningKey::generate();
        let agreement = KeyAgreementSecret::generate();
        let descriptor = DeviceDescriptor::new(
            DeviceId::new(),
            DeviceKind::Desktop,
            name,
            signing.public_key(),
            agreement.public_key(),
        )
        .expect("valid descriptor");
        TestDevice {
            descriptor,
            signing,
            agreement,
        }
    }

    fn transcript(requester: &TestDevice, helper: &TestDevice) -> ImageAssistTranscript {
        ImageAssistTranscript {
            protocol_version: CURRENT_PROTOCOL_VERSION,
            match_id: MatchId::new(),
            requester: requester.descriptor.clone(),
            helper: helper.descriptor.clone(),
            offerer: helper.descriptor.device_id,
            session_id: SessionId::new(),
            ice_servers: vec!["stun:stun.example.test:3478".to_string()],
            expires_at_unix_ms: 1_800_000_000_000,
            request_digest: [3_u8; 32],
        }
    }

    fn entry(name: &str) -> ImageArtifactEntry {
        ImageArtifactEntry {
            name: name.to_string(),
            size_bytes: 1024,
            mime: "image/png".to_string(),
            sha256: digest(),
        }
    }

    #[test]
    fn image_assist_tags_do_not_collide_with_compute_tags() {
        let compute = serde_json::to_value(ComputeWireMessage::ArtifactRead {
            job_id: ComputeJobId::new(),
            path: "out/image.png".to_string(),
            offset: 0,
            max_bytes: 1024,
        })
        .expect("compute frame encodes");
        let image = serde_json::to_value(ImageAssistWireMessage::ArtifactRead {
            request_id: RequestId::new(),
            name: "image-01.png".to_string(),
            offset: 0,
            max_bytes: 1024,
        })
        .expect("image frame encodes");

        assert_eq!(compute["type"], "artifact_read");
        assert_eq!(image["type"], "image_artifact_read");
        assert_ne!(compute["type"], image["type"]);
    }

    #[test]
    fn helper_renew_carries_no_public_profile_metadata() {
        let encoded =
            serde_json::to_value(ImageAssistClientFrame::HelperRenew { lease_ms: 60_000 })
                .expect("renewal encodes");
        assert_eq!(encoded["op"], "helper_renew");
        assert!(encoded.get("display_name").is_none());
        assert!(encoded.get("location").is_none());
    }

    #[test]
    fn a_compute_frame_does_not_decode_as_an_image_assist_frame() {
        for compute in [
            ComputeWireMessage::ArtifactRead {
                job_id: ComputeJobId::new(),
                path: "out/image.png".to_string(),
                offset: 0,
                max_bytes: 1024,
            },
            ComputeWireMessage::Cancel {
                job_id: ComputeJobId::new(),
            },
        ] {
            let encoded = serde_json::to_vec(&compute).expect("compute frame encodes");
            let decoded = serde_json::from_slice::<ImageAssistWireMessage>(&encoded);
            assert!(
                decoded.is_err(),
                "compute frame must not decode as an Image Assist frame: {compute:?}"
            );
        }
    }

    #[test]
    fn an_image_assist_frame_does_not_decode_as_a_compute_frame() {
        let image = ImageAssistWireMessage::Request {
            request_id: RequestId::new(),
            prompt: "a wind turbine at dusk".to_string(),
            aspect_ratio: Some("16:9".to_string()),
        };
        let encoded = serde_json::to_vec(&image).expect("image frame encodes");
        assert!(serde_json::from_slice::<ComputeWireMessage>(&encoded).is_err());
    }

    #[test]
    fn prompt_length_is_bounded_in_utf8_bytes_not_characters() {
        // Well under the 120,000-character tool ceiling, but over the byte cap.
        let prompt = "字".repeat(3_000);
        assert_eq!(prompt.chars().count(), 3_000);
        assert!(prompt.len() > IMAGE_ASSIST_MAX_PROMPT_BYTES);
        let message = ImageAssistWireMessage::Request {
            request_id: RequestId::new(),
            prompt,
            aspect_ratio: None,
        };
        assert_eq!(message.validate(), Err(ImageAssistError::PromptTooLong));
    }

    #[test]
    fn artifact_names_reject_traversal_and_absolute_paths() {
        for name in [
            "../escape.png",
            "nested/image.png",
            "nested\\image.png",
            "C:/image.png",
            ".hidden.png",
            "-leading.png",
            "image.exe",
            "image",
            "IMAGE-01.PNG",
            "",
        ] {
            assert_eq!(
                validate_artifact_name(name),
                Err(ImageAssistError::InvalidArtifactName),
                "name must be rejected: {name}"
            );
        }
        assert!(validate_artifact_name("image-01.png").is_ok());
        assert!(validate_artifact_name("image-01.webp").is_ok());
    }

    #[test]
    fn manifest_rejects_duplicate_names_rather_than_dropping_one() {
        let manifest = vec![entry("image-01.png"), entry("image-01.png")];
        assert_eq!(
            validate_artifact_manifest(&manifest),
            Err(ImageAssistError::DuplicateArtifactName)
        );
    }

    #[test]
    fn manifest_rejects_an_oversized_total_even_when_each_entry_fits() {
        let manifest: Vec<_> = (0..4)
            .map(|index| ImageArtifactEntry {
                name: format!("image-{index:02}.png"),
                size_bytes: IMAGE_ASSIST_MAX_ARTIFACT_BYTES,
                mime: "image/png".to_string(),
                sha256: digest(),
            })
            .collect();
        for artifact in &manifest {
            assert!(artifact.validate().is_ok());
        }
        assert_eq!(
            validate_artifact_manifest(&manifest),
            Err(ImageAssistError::ManifestTooLarge)
        );
    }

    #[test]
    fn manifest_rejects_more_entries_than_the_brokered_limit() {
        let manifest: Vec<_> = (0..=IMAGE_ASSIST_MAX_ARTIFACTS)
            .map(|index| entry(&format!("image-{index:02}.png")))
            .collect();
        assert_eq!(
            validate_artifact_manifest(&manifest),
            Err(ImageAssistError::TooManyArtifacts)
        );
    }

    #[test]
    fn digests_must_be_lowercase_hexadecimal() {
        let mut artifact = entry("image-01.png");
        artifact.sha256 = "A".repeat(64);
        assert_eq!(artifact.validate(), Err(ImageAssistError::InvalidDigest));
        artifact.sha256 = "a".repeat(63);
        assert_eq!(artifact.validate(), Err(ImageAssistError::InvalidDigest));
    }

    #[test]
    fn both_peers_verify_the_match_transcript_and_agree_on_roles() {
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let transcript = transcript(&requester, &helper);

        let requester_proof = transcript
            .sign(&requester.signing)
            .expect("requester signs");
        let helper_proof = transcript.sign(&helper.signing).expect("helper signs");

        assert!(transcript
            .verify(requester.descriptor.device_id, &requester_proof)
            .is_ok());
        assert!(transcript
            .verify(helper.descriptor.device_id, &helper_proof)
            .is_ok());
        assert_eq!(
            transcript.role_of(helper.descriptor.device_id),
            Some(P2pRole::Offerer)
        );
        assert_eq!(
            transcript.role_of(requester.descriptor.device_id),
            Some(P2pRole::Answerer)
        );
    }

    #[test]
    fn tampering_with_the_peer_display_name_breaks_the_transcript() {
        // The approval dialog shows the peer's display name, so an unsigned
        // name would let a malicious introducer relabel who is asking.
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let transcript = transcript(&requester, &helper);
        let proof = transcript
            .sign(&requester.signing)
            .expect("requester signs");

        let mut tampered = transcript.clone();
        tampered.requester = DeviceDescriptor::new(
            requester.descriptor.device_id,
            requester.descriptor.kind,
            "someone you trust",
            requester.descriptor.signing_public_key,
            requester.descriptor.key_agreement_public_key,
        )
        .expect("valid descriptor");

        assert_ne!(
            transcript.signature_transcript().expect("original bytes"),
            tampered.signature_transcript().expect("tampered bytes")
        );
        assert_eq!(
            tampered.verify(requester.descriptor.device_id, &proof),
            Err(ImageAssistError::InvalidTranscriptProof)
        );
    }

    #[test]
    fn tampering_with_the_assigned_role_breaks_the_transcript() {
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let transcript = transcript(&requester, &helper);
        let proof = transcript.sign(&helper.signing).expect("helper signs");

        let mut tampered = transcript.clone();
        tampered.offerer = requester.descriptor.device_id;

        assert_eq!(
            tampered.verify(helper.descriptor.device_id, &proof),
            Err(ImageAssistError::InvalidTranscriptProof)
        );
    }

    #[test]
    fn a_third_device_cannot_present_a_transcript_proof() {
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let outsider = device("outsider");
        let transcript = transcript(&requester, &helper);
        let proof = transcript.sign(&outsider.signing).expect("outsider signs");

        assert_eq!(
            transcript.verify(outsider.descriptor.device_id, &proof),
            Err(ImageAssistError::UnknownSigner)
        );
    }

    #[test]
    fn transcripts_require_sorted_deduplicated_ice_servers() {
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let mut transcript = transcript(&requester, &helper);

        transcript.ice_servers = vec![
            "stun:b.example.test:3478".to_string(),
            "stun:a.example.test:3478".to_string(),
        ];
        assert_eq!(
            transcript.validate(),
            Err(ImageAssistError::UnsortedIceServers)
        );

        transcript.ice_servers = vec![
            "stun:a.example.test:3478".to_string(),
            "stun:a.example.test:3478".to_string(),
        ];
        assert_eq!(
            transcript.validate(),
            Err(ImageAssistError::UnsortedIceServers)
        );
    }

    #[test]
    fn a_transcript_frame_is_validated_by_the_decoder_itself() {
        // The transcript is the first frame on the channel, so it is decoded
        // before any Image Assist state exists to check it. Frame validation is
        // therefore the only thing standing between a malformed transcript and
        // the verification path.
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let mut transcript = transcript(&requester, &helper);
        let proof = transcript.sign(&helper.signing).expect("helper signs");

        let frame = ImageAssistWireMessage::Transcript {
            transcript: Box::new(transcript.clone()),
            proof: proof.clone(),
        };
        assert_eq!(frame.validate(), Ok(()));
        let encoded = serde_json::to_value(&frame).expect("transcript frame encodes");
        assert_eq!(encoded["type"], "image_transcript");
        assert!(serde_json::from_value::<ComputeWireMessage>(encoded).is_err());

        transcript.ice_servers = vec![
            "stun:b.example.test:3478".to_string(),
            "stun:a.example.test:3478".to_string(),
        ];
        assert_eq!(
            ImageAssistWireMessage::Transcript {
                transcript: Box::new(transcript),
                proof,
            }
            .validate(),
            Err(ImageAssistError::UnsortedIceServers)
        );
    }

    #[test]
    fn both_peers_derive_the_same_preview_key() {
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let match_id = MatchId::new();
        let context = PreviewKeyContext::new(
            match_id,
            requester.descriptor.device_id,
            helper.descriptor.device_id,
        )
        .expect("preview context");

        let sealed_by_requester = requester
            .agreement
            .derive_preview_key(&helper.descriptor.key_agreement_public_key, &context)
            .expect("requester derives");
        let opened_by_helper = helper
            .agreement
            .derive_preview_key(&requester.descriptor.key_agreement_public_key, &context)
            .expect("helper derives");

        assert_eq!(sealed_by_requester.as_bytes(), opened_by_helper.as_bytes());
    }

    #[test]
    fn the_preview_key_is_domain_separated_from_the_transport_key() {
        // Even when a match id and a transport session id carry the same UUID,
        // the two derivations must not collide: a shared key would let a
        // preview envelope consume the transport replay window.
        let requester = device("requester laptop");
        let helper = device("helper workstation");
        let shared = uuid::Uuid::new_v4();

        let preview = requester
            .agreement
            .derive_preview_key(
                &helper.descriptor.key_agreement_public_key,
                &PreviewKeyContext::new(
                    MatchId::from_uuid(shared),
                    requester.descriptor.device_id,
                    helper.descriptor.device_id,
                )
                .expect("preview context"),
            )
            .expect("preview key");
        let transport = requester
            .agreement
            .derive_session_key(
                &helper.descriptor.key_agreement_public_key,
                &SessionKeyContext::new(
                    SessionId::from_uuid(shared),
                    requester.descriptor.device_id,
                    helper.descriptor.device_id,
                )
                .expect("session context"),
            )
            .expect("transport key");

        assert_ne!(preview.as_bytes(), transport.as_bytes());
    }

    #[test]
    fn chunk_requests_are_bounded_by_the_transfer_limit() {
        let message = ImageAssistWireMessage::ArtifactRead {
            request_id: RequestId::new(),
            name: "image-01.png".to_string(),
            offset: 0,
            max_bytes: IMAGE_ASSIST_MAX_ARTIFACT_CHUNK_BYTES as u32 + 1,
        };
        assert_eq!(
            message.validate(),
            Err(ImageAssistError::InvalidChunkRequest)
        );
    }
}
